[General]
Background="/usr/share/sddm/themes/sugar-candy/Backgrounds/wallpaper.jpg"
BlurRadius=40
FormPosition="center"
ScreenWidth=1920
ScreenHeight=1080
MainColor="#cdd6f4"
AccentColor="#cba6f7"
BackgroundColor="#1e1e2e"
OverrideLoginButtonTextColor="#1e1e2e"
InterfaceShadowSize=6
InterfaceShadowOpacity=0.6
RoundCorners=12
ScreenPadding=0
Font="JetBrainsMono Nerd Font"
FontSize=12
DateFormat="dddd, d MMMM yyyy"
HeaderText="Welcome"
ForceHideCompletePassword=true
